// export const CREATE_COURSE = 'CREATE_COURSE';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSE_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';


export const PRODUCT_JSON_LAST_UPDATED = 'PRODUCT_JSON_LAST_UPDATED'
export const PRODUCT_JSON_FILE_UPLOAD = 'PRODUCT_JSON_FILE_UPLOAD'
export const LOOK_JSON_FILE_UPLOAD = 'LOOK_JSON_FILE_UPLOAD'
export const PRODUCTS_POST_FILE_URL = 'http://localhost:3000/api/2/region/test/json/'
export const LOOKS_POST_FILE_URL = 'LOOK_JSON_FILE_UPLOAD'
export const PRODUCTS_JSON_VALID_CHECK = 'PRODUCTS_JSON_VALID_CHECK'
export const LOOKS_JSON_VALID_CHECK = 'LOOKS_JSON_VALID_CHECK'
